name: CI/CD Pipeline for Client and Server

on:
  push:
    branches:
      - dev
      - master

jobs:
  build-and-test-client:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Node.js para client
      - name: Set up Node.js for client
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      # Paso 3: Instalar dependencias de client
      - name: Install client dependencies
        run: npm install
        working-directory: client

      - name: Set environment for OpenSSL
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      # Paso 4: Ejecutar pruebas de client
      - name: Run client tests
        run: npm test -- --watchAll=false
        working-directory: client

      # Paso 5: Construir la aplicación client
      - name: Build client application
        run: npm run build
        working-directory: client

  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Node.js para server
      - name: Set up Node.js for server
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      # Paso 3: Instalar dependencias de server
      - name: Install server dependencies
        run: npm install
        working-directory: server

      # Paso 4: Ejecutar pruebas de server
      - name: Run server tests
        run: npm test -- --passWithNoTests
        working-directory: server

